version: "3.8"
services:
  db:
    image: postgres:15
    container_name: payu_postgres
    restart: always
    environment:
      POSTGRES_USER: payu
      POSTGRES_PASSWORD: payu123
      POSTGRES_DB: payudb
    ports:
      - "5432:5432"
    volumes:
      - payu_data:/var/lib/postgresql/data

volumes:
  payu_data:
